vich_uploader:
    db_driver: orm

    mappings:
        profilePicture:
            uri_prefix: /images/profilePicture
            upload_destination: '%kernel.project_dir%/public/images/profilePicture'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        cv:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        passport:
            uri_prefix: /images/passport
            upload_destination: '%kernel.project_dir%/public/images/passport'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        documents:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer